# V3 Data Query System - Production Docker Compose
version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: v3-backend:latest
    container_name: v3-backend
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app_v3.py
      - GUNICORN_WORKERS=2
      - GUNICORN_THREADS=4
      - PLAYWRIGHT_HEADLESS=true
      - DISABLE_GPU=true
      - DISABLE_DEV_SHM=true
      - LOW_RESOURCE_MODE=true
      - TZ=Asia/Shanghai
    volumes:
      - ./logs:/app/logs
      - ./temp:/app/temp
    networks:
      - v3-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: v3-frontend:latest
    container_name: v3-frontend
    restart: unless-stopped
    ports:
      - "80:8080"
    depends_on:
      - backend
    networks:
      - v3-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/frontend-health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  # Redis cache (optional)
  redis:
    image: redis:7-alpine
    container_name: v3-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - v3-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M

volumes:
  redis_data:
    driver: local

networks:
  v3-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16